interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    ".", "src/jsonmlir",
]

[[modules ]]
path = "src.jsonmlir.operations.codegen"
depends_on = []

[[modules ]]
path = "src.jsonmlir.pipeline.commands"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.same_types"
depends_on = []

[[modules ]]
path = "src.jsonmlir.pipeline.cli"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_module"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.base"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_set"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_alloc"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_math"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.trace"
depends_on = []

[[modules ]]
path = "src.jsonmlir.variables.var"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.discard_builder"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_unary"
depends_on = []

[[modules ]]
path = "src.jsonmlir.schema.clean_for_ts"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_alloca"
depends_on = []

[[modules ]]
path = "src.jsonmlir.pipeline.compiler"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_constant"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.block"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_call"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_var"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils"
depends_on = []

[[modules ]]
path = "src.jsonmlir.pipeline"
depends_on = []

[[modules ]]
path = "src.jsonmlir.variables.memory"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.schema_shape"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.ssa_dim"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_function"
depends_on = []

[[modules ]]
path = "src.jsonmlir.variables"
depends_on = []

[[modules ]]
path = "src.jsonmlir.schema.export"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_cond"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.bare_ptr"
depends_on = []

[[modules ]]
path = "src.jsonmlir.schema"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.enum_scalars"
depends_on = []

[[modules ]]
path = "src.jsonmlir.variables.ty"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_define_function"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_binary"
depends_on = []

[[modules ]]
path = "src.jsonmlir.variables.val"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.block_entry"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_define_struct"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.ssa_val"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_while"
depends_on = []

[[modules ]]
path = "src.jsonmlir.variables.factory"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.dsl"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_print"
depends_on = []

[[modules ]]
path = "src.jsonmlir.variables.struct_field"
depends_on = []

[[modules ]]
path = "src.jsonmlir.utils.ssa_check"
depends_on = []

[[modules ]]
path = "src.jsonmlir.operations.op_operator"
depends_on = []
